services:
  flask:
    container_name: varmerger_service
    restart: always
    build: 
        context: .
        dockerfile: ./app/flask/Dockerfile
        network: host
        args:
                progress: string
    ports:
      - "6666:6666"
        #command: "tail -f /dev/null"
    command: gunicorn -w 1 -b 0.0.0.0:6666 wsgi:app
    depends_on:
      - seqrepo_api
    volumes:
      - type: bind
        source: /mnt/c/Users/judson.x.belmont/repos/varmerger/app/flask/config
        target: /app/config
  
  # nginx:
  #   container_name: varmerger_nginx
  #   restart: always
  #   build:
  #       context: .
  #       dockerfile: ./app/nginx/Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - flask

  # TODO
  # seqrepo:
  #   container_name: seqrepo
  #   image: biocommons/seqrepo
  #   restart: always
  #   ports:
  #     - "7777:5000"

  seqrepo_api:
    container_name: seqrepo_rest_service
    image: biocommons/seqrepo-rest-service
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /usr/local/share/seqrepo/2024-02-20
        target: /mnt/seqrepo
    command: ["seqrepo-rest-service","/mnt/seqrepo","-w"]