version: '3.3'

services:
  flask:
    container_name: varmerger_rest-service
    restart: always
    build: 
        context: .
        dockerfile: ./app/flask/Dockerfile
        args:
                progress: string
    ports:
      - "6666:6666"
        #command: "tail -f /dev/null"
    command: gunicorn -w 1 -b 0.0.0.0:6666 wsgi:app
    depends_on:
      - seqrepo_api
    volumes:
      - type: bind
        source: /mnt/c/Users/judson.x.belmont/Documents/Code/varmerger/app/flask/config
        target: /config
  
  nginx:
    container_name: varmerger_nginx
    restart: always
    build:
        context: .
        dockerfile: ./app/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - flask

  seqrepo_api:
    container_name: seqrepo_rest-service
    image: biocommons/seqrepo-rest-service
    restart: always
    ports:
      - "7777:5000"
