version: '1.0.0'

services:
  flask:
    container_name: varmerger_flask
    restart: always
    build: 
        context: .
        dockerfile: ./app/flask/Dockerfile
        args:
                progress: string
    ports:
      - "6666:6666"
    command: "tail -f /dev/null"
    #command: gunicorn -w 1 -b 0.0.0.0:6666 wsgi:server
  
  nginx:
    container_name: varmerger_nginx
    restart: always
    build:
        context: .
        dockerfile: ./app/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - varmerger_flask
