version: 1
formatters:
  default: 
    format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
handlers:
        #  wsgi:
        #  level: 'DEBUG'
        #  class: 'logging.StreamHandler'
        #  stream: 'ext://sys.stdout'
        #  formatter: 'default'

  console:
          level: 'INFO'
          class: 'logging.StreamHandler'
          stream: 'ext://sys.stdout'
          formatter: 'default'

  file:
          level: 'DEBUG'
          class: 'logging.FileHandler'
          filename: '/home/belmjud/varchemist.log'
          formatter: 'default'
root:
        level: 'INFO'
        handlers:
                #  - 'wsgi'
           - 'console'
           - 'file'
